//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}bracketattachment" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}bracketedgroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BracketedObjectIDs" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BracketUsage"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Anypolymer"/&gt;
 *             &lt;enumeration value="Component"/&gt;
 *             &lt;enumeration value="Copolymer"/&gt;
 *             &lt;enumeration value="CopolymerAlternating"/&gt;
 *             &lt;enumeration value="CopolymerBlock"/&gt;
 *             &lt;enumeration value="CopolymerRandom"/&gt;
 *             &lt;enumeration value="Crosslink"/&gt;
 *             &lt;enumeration value="Generic"/&gt;
 *             &lt;enumeration value="Graft"/&gt;
 *             &lt;enumeration value="Mer"/&gt;
 *             &lt;enumeration value="MixtureOrdered"/&gt;
 *             &lt;enumeration value="MixtureUnordered"/&gt;
 *             &lt;enumeration value="Modification"/&gt;
 *             &lt;enumeration value="Monomer"/&gt;
 *             &lt;enumeration value="MultipleGroup"/&gt;
 *             &lt;enumeration value="SRU"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PolymerRepeatPattern"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="HeadToTail"/&gt;
 *             &lt;enumeration value="HeadToHead"/&gt;
 *             &lt;enumeration value="EitherUnknown"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PolymerFlipType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="NoFlip"/&gt;
 *             &lt;enumeration value="Flip"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RepeatCount" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ComponentOrder" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="SRULabel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bracketattachment",
    "bracketedgroup"
})
@XmlRootElement(name = "bracketedgroup")
public class Bracketedgroup {

    @XmlElement(required = true)
    protected List<Bracketattachment> bracketattachment;
    protected List<Bracketedgroup> bracketedgroup;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "BracketedObjectIDs")
    @XmlSchemaType(name = "anySimpleType")
    protected String bracketedObjectIDs;
    @XmlAttribute(name = "BracketUsage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bracketUsage;
    @XmlAttribute(name = "PolymerRepeatPattern")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String polymerRepeatPattern;
    @XmlAttribute(name = "PolymerFlipType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String polymerFlipType;
    @XmlAttribute(name = "RepeatCount")
    @XmlSchemaType(name = "anySimpleType")
    protected String repeatCount;
    @XmlAttribute(name = "ComponentOrder")
    @XmlSchemaType(name = "anySimpleType")
    protected String componentOrder;
    @XmlAttribute(name = "SRULabel")
    @XmlSchemaType(name = "anySimpleType")
    protected String sruLabel;

    /**
     * Gets the value of the bracketattachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bracketattachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBracketattachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bracketattachment }
     * 
     * 
     */
    public List<Bracketattachment> getBracketattachment() {
        if (bracketattachment == null) {
            bracketattachment = new ArrayList<Bracketattachment>();
        }
        return this.bracketattachment;
    }

    /**
     * Gets the value of the bracketedgroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bracketedgroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBracketedgroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bracketedgroup }
     * 
     * 
     */
    public List<Bracketedgroup> getBracketedgroup() {
        if (bracketedgroup == null) {
            bracketedgroup = new ArrayList<Bracketedgroup>();
        }
        return this.bracketedgroup;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the bracketedObjectIDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBracketedObjectIDs() {
        return bracketedObjectIDs;
    }

    /**
     * Sets the value of the bracketedObjectIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBracketedObjectIDs(String value) {
        this.bracketedObjectIDs = value;
    }

    /**
     * Gets the value of the bracketUsage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBracketUsage() {
        return bracketUsage;
    }

    /**
     * Sets the value of the bracketUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBracketUsage(String value) {
        this.bracketUsage = value;
    }

    /**
     * Gets the value of the polymerRepeatPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolymerRepeatPattern() {
        return polymerRepeatPattern;
    }

    /**
     * Sets the value of the polymerRepeatPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolymerRepeatPattern(String value) {
        this.polymerRepeatPattern = value;
    }

    /**
     * Gets the value of the polymerFlipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolymerFlipType() {
        return polymerFlipType;
    }

    /**
     * Sets the value of the polymerFlipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolymerFlipType(String value) {
        this.polymerFlipType = value;
    }

    /**
     * Gets the value of the repeatCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepeatCount() {
        return repeatCount;
    }

    /**
     * Sets the value of the repeatCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepeatCount(String value) {
        this.repeatCount = value;
    }

    /**
     * Gets the value of the componentOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentOrder() {
        return componentOrder;
    }

    /**
     * Sets the value of the componentOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentOrder(String value) {
        this.componentOrder = value;
    }

    /**
     * Gets the value of the sruLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRULabel() {
        return sruLabel;
    }

    /**
     * Sets the value of the sruLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRULabel(String value) {
        this.sruLabel = value;
    }

}
