//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}colortable" minOccurs="0"/&gt;
 *         &lt;element ref="{}fonttable" minOccurs="0"/&gt;
 *         &lt;element ref="{}page" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{}templategrid" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="MacPrintInfo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="WinPrintInfo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="PrintMargins" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ChainAngle" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BondSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BondLength" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BoldWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="MarginWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="HashSpacing" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelFont" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelFace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelColor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelLineHeight" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelJustification" default="Left"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Auto"/&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Above"/&gt;
 *             &lt;enumeration value="Below"/&gt;
 *             &lt;enumeration value="Best"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="CaptionFont" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionFace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionColor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionLineHeight" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionJustification" default="Left"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Auto"/&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Full"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="FractionalWidths" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="InterpretChemically" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomQuery" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomStereo" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomEnhancedStereo" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomNumber" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowBondQuery" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowBondStereo" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowBondRxn" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowTerminalCarbonLabels" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowNonTerminalCarbonLabels" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HideImplicitHydrogens" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Magnification" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="WindowIsZoomed" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="WindowPosition" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="WindowSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CreationUserName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CreationProgram" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ModificationUserName" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ModificationDate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ModificationProgram" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Comment" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CartridgeData" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="FixInPlaceExtent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="FixInPlaceGap" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "colortable",
    "fonttable",
    "page",
    "templategrid"
})
@XmlRootElement(name = "CDXML")
public class CDXML {

    protected Colortable colortable;
    protected Fonttable fonttable;
    @XmlElement(required = true)
    protected List<Page> page;
    protected Templategrid templategrid;
    @XmlAttribute(name = "BoundingBox")
    @XmlSchemaType(name = "anySimpleType")
    protected String boundingBox;
    @XmlAttribute(name = "MacPrintInfo")
    @XmlSchemaType(name = "anySimpleType")
    protected String macPrintInfo;
    @XmlAttribute(name = "WinPrintInfo")
    @XmlSchemaType(name = "anySimpleType")
    protected String winPrintInfo;
    @XmlAttribute(name = "PrintMargins")
    @XmlSchemaType(name = "anySimpleType")
    protected String printMargins;
    @XmlAttribute(name = "ChainAngle")
    @XmlSchemaType(name = "anySimpleType")
    protected String chainAngle;
    @XmlAttribute(name = "BondSpacing")
    @XmlSchemaType(name = "anySimpleType")
    protected String bondSpacing;
    @XmlAttribute(name = "BondLength")
    @XmlSchemaType(name = "anySimpleType")
    protected String bondLength;
    @XmlAttribute(name = "BoldWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String boldWidth;
    @XmlAttribute(name = "LineWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String lineWidth;
    @XmlAttribute(name = "MarginWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String marginWidth;
    @XmlAttribute(name = "HashSpacing")
    @XmlSchemaType(name = "anySimpleType")
    protected String hashSpacing;
    @XmlAttribute(name = "LabelFont")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelFont;
    @XmlAttribute(name = "LabelSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelSize;
    @XmlAttribute(name = "LabelFace")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelFace;
    @XmlAttribute(name = "LabelColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelColor;
    @XmlAttribute(name = "LabelLineHeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelLineHeight;
    @XmlAttribute(name = "LabelJustification")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String labelJustification;
    @XmlAttribute(name = "CaptionFont")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionFont;
    @XmlAttribute(name = "CaptionSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionSize;
    @XmlAttribute(name = "CaptionFace")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionFace;
    @XmlAttribute(name = "CaptionColor")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionColor;
    @XmlAttribute(name = "CaptionLineHeight")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionLineHeight;
    @XmlAttribute(name = "CaptionJustification")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String captionJustification;
    @XmlAttribute(name = "FractionalWidths")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fractionalWidths;
    @XmlAttribute(name = "InterpretChemically")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String interpretChemically;
    @XmlAttribute(name = "ShowAtomQuery")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomQuery;
    @XmlAttribute(name = "ShowAtomStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomStereo;
    @XmlAttribute(name = "ShowAtomEnhancedStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomEnhancedStereo;
    @XmlAttribute(name = "ShowAtomNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomNumber;
    @XmlAttribute(name = "ShowBondQuery")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showBondQuery;
    @XmlAttribute(name = "ShowBondStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showBondStereo;
    @XmlAttribute(name = "ShowBondRxn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showBondRxn;
    @XmlAttribute(name = "ShowTerminalCarbonLabels")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showTerminalCarbonLabels;
    @XmlAttribute(name = "ShowNonTerminalCarbonLabels")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showNonTerminalCarbonLabels;
    @XmlAttribute(name = "HideImplicitHydrogens")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hideImplicitHydrogens;
    @XmlAttribute(name = "Magnification")
    @XmlSchemaType(name = "anySimpleType")
    protected String magnification;
    @XmlAttribute(name = "WindowIsZoomed")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String windowIsZoomed;
    @XmlAttribute(name = "WindowPosition")
    @XmlSchemaType(name = "anySimpleType")
    protected String windowPosition;
    @XmlAttribute(name = "WindowSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String windowSize;
    @XmlAttribute(name = "CreationUserName")
    @XmlSchemaType(name = "anySimpleType")
    protected String creationUserName;
    @XmlAttribute(name = "CreationDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String creationDate;
    @XmlAttribute(name = "CreationProgram")
    @XmlSchemaType(name = "anySimpleType")
    protected String creationProgram;
    @XmlAttribute(name = "ModificationUserName")
    @XmlSchemaType(name = "anySimpleType")
    protected String modificationUserName;
    @XmlAttribute(name = "ModificationDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String modificationDate;
    @XmlAttribute(name = "ModificationProgram")
    @XmlSchemaType(name = "anySimpleType")
    protected String modificationProgram;
    @XmlAttribute(name = "Name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "Comment")
    @XmlSchemaType(name = "anySimpleType")
    protected String comment;
    @XmlAttribute(name = "CartridgeData")
    @XmlSchemaType(name = "anySimpleType")
    protected String cartridgeData;
    @XmlAttribute(name = "FixInPlaceExtent")
    @XmlSchemaType(name = "anySimpleType")
    protected String fixInPlaceExtent;
    @XmlAttribute(name = "FixInPlaceGap")
    @XmlSchemaType(name = "anySimpleType")
    protected String fixInPlaceGap;

    /**
     * Gets the value of the colortable property.
     * 
     * @return
     *     possible object is
     *     {@link Colortable }
     *     
     */
    public Colortable getColortable() {
        return colortable;
    }

    /**
     * Sets the value of the colortable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Colortable }
     *     
     */
    public void setColortable(Colortable value) {
        this.colortable = value;
    }

    /**
     * Gets the value of the fonttable property.
     * 
     * @return
     *     possible object is
     *     {@link Fonttable }
     *     
     */
    public Fonttable getFonttable() {
        return fonttable;
    }

    /**
     * Sets the value of the fonttable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fonttable }
     *     
     */
    public void setFonttable(Fonttable value) {
        this.fonttable = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Page }
     * 
     * 
     */
    public List<Page> getPage() {
        if (page == null) {
            page = new ArrayList<Page>();
        }
        return this.page;
    }

    /**
     * Gets the value of the templategrid property.
     * 
     * @return
     *     possible object is
     *     {@link Templategrid }
     *     
     */
    public Templategrid getTemplategrid() {
        return templategrid;
    }

    /**
     * Sets the value of the templategrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Templategrid }
     *     
     */
    public void setTemplategrid(Templategrid value) {
        this.templategrid = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the macPrintInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacPrintInfo() {
        return macPrintInfo;
    }

    /**
     * Sets the value of the macPrintInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacPrintInfo(String value) {
        this.macPrintInfo = value;
    }

    /**
     * Gets the value of the winPrintInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWinPrintInfo() {
        return winPrintInfo;
    }

    /**
     * Sets the value of the winPrintInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWinPrintInfo(String value) {
        this.winPrintInfo = value;
    }

    /**
     * Gets the value of the printMargins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintMargins() {
        return printMargins;
    }

    /**
     * Sets the value of the printMargins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintMargins(String value) {
        this.printMargins = value;
    }

    /**
     * Gets the value of the chainAngle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChainAngle() {
        return chainAngle;
    }

    /**
     * Sets the value of the chainAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChainAngle(String value) {
        this.chainAngle = value;
    }

    /**
     * Gets the value of the bondSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondSpacing() {
        return bondSpacing;
    }

    /**
     * Sets the value of the bondSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondSpacing(String value) {
        this.bondSpacing = value;
    }

    /**
     * Gets the value of the bondLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondLength() {
        return bondLength;
    }

    /**
     * Sets the value of the bondLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondLength(String value) {
        this.bondLength = value;
    }

    /**
     * Gets the value of the boldWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoldWidth() {
        return boldWidth;
    }

    /**
     * Sets the value of the boldWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoldWidth(String value) {
        this.boldWidth = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineWidth(String value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the marginWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarginWidth() {
        return marginWidth;
    }

    /**
     * Sets the value of the marginWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarginWidth(String value) {
        this.marginWidth = value;
    }

    /**
     * Gets the value of the hashSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashSpacing() {
        return hashSpacing;
    }

    /**
     * Sets the value of the hashSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashSpacing(String value) {
        this.hashSpacing = value;
    }

    /**
     * Gets the value of the labelFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelFont() {
        return labelFont;
    }

    /**
     * Sets the value of the labelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelFont(String value) {
        this.labelFont = value;
    }

    /**
     * Gets the value of the labelSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelSize() {
        return labelSize;
    }

    /**
     * Sets the value of the labelSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelSize(String value) {
        this.labelSize = value;
    }

    /**
     * Gets the value of the labelFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelFace() {
        return labelFace;
    }

    /**
     * Sets the value of the labelFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelFace(String value) {
        this.labelFace = value;
    }

    /**
     * Gets the value of the labelColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelColor() {
        return labelColor;
    }

    /**
     * Sets the value of the labelColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelColor(String value) {
        this.labelColor = value;
    }

    /**
     * Gets the value of the labelLineHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelLineHeight() {
        return labelLineHeight;
    }

    /**
     * Sets the value of the labelLineHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelLineHeight(String value) {
        this.labelLineHeight = value;
    }

    /**
     * Gets the value of the labelJustification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelJustification() {
        if (labelJustification == null) {
            return "Left";
        } else {
            return labelJustification;
        }
    }

    /**
     * Sets the value of the labelJustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelJustification(String value) {
        this.labelJustification = value;
    }

    /**
     * Gets the value of the captionFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFont() {
        return captionFont;
    }

    /**
     * Sets the value of the captionFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFont(String value) {
        this.captionFont = value;
    }

    /**
     * Gets the value of the captionSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionSize() {
        return captionSize;
    }

    /**
     * Sets the value of the captionSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionSize(String value) {
        this.captionSize = value;
    }

    /**
     * Gets the value of the captionFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFace() {
        return captionFace;
    }

    /**
     * Sets the value of the captionFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFace(String value) {
        this.captionFace = value;
    }

    /**
     * Gets the value of the captionColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionColor() {
        return captionColor;
    }

    /**
     * Sets the value of the captionColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionColor(String value) {
        this.captionColor = value;
    }

    /**
     * Gets the value of the captionLineHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionLineHeight() {
        return captionLineHeight;
    }

    /**
     * Sets the value of the captionLineHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionLineHeight(String value) {
        this.captionLineHeight = value;
    }

    /**
     * Gets the value of the captionJustification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionJustification() {
        if (captionJustification == null) {
            return "Left";
        } else {
            return captionJustification;
        }
    }

    /**
     * Sets the value of the captionJustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionJustification(String value) {
        this.captionJustification = value;
    }

    /**
     * Gets the value of the fractionalWidths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFractionalWidths() {
        if (fractionalWidths == null) {
            return "no";
        } else {
            return fractionalWidths;
        }
    }

    /**
     * Sets the value of the fractionalWidths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFractionalWidths(String value) {
        this.fractionalWidths = value;
    }

    /**
     * Gets the value of the interpretChemically property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpretChemically() {
        if (interpretChemically == null) {
            return "yes";
        } else {
            return interpretChemically;
        }
    }

    /**
     * Sets the value of the interpretChemically property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpretChemically(String value) {
        this.interpretChemically = value;
    }

    /**
     * Gets the value of the showAtomQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomQuery() {
        if (showAtomQuery == null) {
            return "yes";
        } else {
            return showAtomQuery;
        }
    }

    /**
     * Sets the value of the showAtomQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomQuery(String value) {
        this.showAtomQuery = value;
    }

    /**
     * Gets the value of the showAtomStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomStereo() {
        if (showAtomStereo == null) {
            return "no";
        } else {
            return showAtomStereo;
        }
    }

    /**
     * Sets the value of the showAtomStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomStereo(String value) {
        this.showAtomStereo = value;
    }

    /**
     * Gets the value of the showAtomEnhancedStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomEnhancedStereo() {
        if (showAtomEnhancedStereo == null) {
            return "yes";
        } else {
            return showAtomEnhancedStereo;
        }
    }

    /**
     * Sets the value of the showAtomEnhancedStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomEnhancedStereo(String value) {
        this.showAtomEnhancedStereo = value;
    }

    /**
     * Gets the value of the showAtomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomNumber() {
        if (showAtomNumber == null) {
            return "no";
        } else {
            return showAtomNumber;
        }
    }

    /**
     * Sets the value of the showAtomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomNumber(String value) {
        this.showAtomNumber = value;
    }

    /**
     * Gets the value of the showBondQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowBondQuery() {
        if (showBondQuery == null) {
            return "yes";
        } else {
            return showBondQuery;
        }
    }

    /**
     * Sets the value of the showBondQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowBondQuery(String value) {
        this.showBondQuery = value;
    }

    /**
     * Gets the value of the showBondStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowBondStereo() {
        if (showBondStereo == null) {
            return "no";
        } else {
            return showBondStereo;
        }
    }

    /**
     * Sets the value of the showBondStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowBondStereo(String value) {
        this.showBondStereo = value;
    }

    /**
     * Gets the value of the showBondRxn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowBondRxn() {
        if (showBondRxn == null) {
            return "yes";
        } else {
            return showBondRxn;
        }
    }

    /**
     * Sets the value of the showBondRxn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowBondRxn(String value) {
        this.showBondRxn = value;
    }

    /**
     * Gets the value of the showTerminalCarbonLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowTerminalCarbonLabels() {
        if (showTerminalCarbonLabels == null) {
            return "no";
        } else {
            return showTerminalCarbonLabels;
        }
    }

    /**
     * Sets the value of the showTerminalCarbonLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowTerminalCarbonLabels(String value) {
        this.showTerminalCarbonLabels = value;
    }

    /**
     * Gets the value of the showNonTerminalCarbonLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowNonTerminalCarbonLabels() {
        if (showNonTerminalCarbonLabels == null) {
            return "no";
        } else {
            return showNonTerminalCarbonLabels;
        }
    }

    /**
     * Sets the value of the showNonTerminalCarbonLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowNonTerminalCarbonLabels(String value) {
        this.showNonTerminalCarbonLabels = value;
    }

    /**
     * Gets the value of the hideImplicitHydrogens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideImplicitHydrogens() {
        if (hideImplicitHydrogens == null) {
            return "no";
        } else {
            return hideImplicitHydrogens;
        }
    }

    /**
     * Sets the value of the hideImplicitHydrogens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideImplicitHydrogens(String value) {
        this.hideImplicitHydrogens = value;
    }

    /**
     * Gets the value of the magnification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMagnification() {
        return magnification;
    }

    /**
     * Sets the value of the magnification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMagnification(String value) {
        this.magnification = value;
    }

    /**
     * Gets the value of the windowIsZoomed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindowIsZoomed() {
        if (windowIsZoomed == null) {
            return "no";
        } else {
            return windowIsZoomed;
        }
    }

    /**
     * Sets the value of the windowIsZoomed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindowIsZoomed(String value) {
        this.windowIsZoomed = value;
    }

    /**
     * Gets the value of the windowPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindowPosition() {
        return windowPosition;
    }

    /**
     * Sets the value of the windowPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindowPosition(String value) {
        this.windowPosition = value;
    }

    /**
     * Gets the value of the windowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWindowSize() {
        return windowSize;
    }

    /**
     * Sets the value of the windowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWindowSize(String value) {
        this.windowSize = value;
    }

    /**
     * Gets the value of the creationUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationUserName() {
        return creationUserName;
    }

    /**
     * Sets the value of the creationUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationUserName(String value) {
        this.creationUserName = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the creationProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationProgram() {
        return creationProgram;
    }

    /**
     * Sets the value of the creationProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationProgram(String value) {
        this.creationProgram = value;
    }

    /**
     * Gets the value of the modificationUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationUserName() {
        return modificationUserName;
    }

    /**
     * Sets the value of the modificationUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationUserName(String value) {
        this.modificationUserName = value;
    }

    /**
     * Gets the value of the modificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationDate() {
        return modificationDate;
    }

    /**
     * Sets the value of the modificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationDate(String value) {
        this.modificationDate = value;
    }

    /**
     * Gets the value of the modificationProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationProgram() {
        return modificationProgram;
    }

    /**
     * Sets the value of the modificationProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationProgram(String value) {
        this.modificationProgram = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the cartridgeData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCartridgeData() {
        return cartridgeData;
    }

    /**
     * Sets the value of the cartridgeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCartridgeData(String value) {
        this.cartridgeData = value;
    }

    /**
     * Gets the value of the fixInPlaceExtent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixInPlaceExtent() {
        return fixInPlaceExtent;
    }

    /**
     * Sets the value of the fixInPlaceExtent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixInPlaceExtent(String value) {
        this.fixInPlaceExtent = value;
    }

    /**
     * Gets the value of the fixInPlaceGap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixInPlaceGap() {
        return fixInPlaceGap;
    }

    /**
     * Sets the value of the fixInPlaceGap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixInPlaceGap(String value) {
        this.fixInPlaceGap = value;
    }

}
