//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}objecttag"/&gt;
 *         &lt;element ref="{}represent"/&gt;
 *         &lt;element ref="{}t"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="SupersededBy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="bgcolor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BoundingBox" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="GraphicType" default="Undefined"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Undefined"/&gt;
 *             &lt;enumeration value="Line"/&gt;
 *             &lt;enumeration value="Arc"/&gt;
 *             &lt;enumeration value="Rectangle"/&gt;
 *             &lt;enumeration value="Oval"/&gt;
 *             &lt;enumeration value="Orbital"/&gt;
 *             &lt;enumeration value="Bracket"/&gt;
 *             &lt;enumeration value="Symbol"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="LineType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Solid"/&gt;
 *             &lt;enumeration value="Dashed"/&gt;
 *             &lt;enumeration value="Bold"/&gt;
 *             &lt;enumeration value="Wavy"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ArrowType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="NoHead"/&gt;
 *             &lt;enumeration value="HalfHead"/&gt;
 *             &lt;enumeration value="FullHead"/&gt;
 *             &lt;enumeration value="Resonance"/&gt;
 *             &lt;enumeration value="Equilibrium"/&gt;
 *             &lt;enumeration value="Hollow"/&gt;
 *             &lt;enumeration value="RetroSynthetic"/&gt;
 *             &lt;enumeration value="NoGo"/&gt;
 *             &lt;enumeration value="Dipole"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="BracketType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="RoundPair"/&gt;
 *             &lt;enumeration value="SquarePair"/&gt;
 *             &lt;enumeration value="CurlyPair"/&gt;
 *             &lt;enumeration value="Square"/&gt;
 *             &lt;enumeration value="Curly"/&gt;
 *             &lt;enumeration value="Round"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RectangleType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="OvalType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="OrbitalType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="s"/&gt;
 *             &lt;enumeration value="p"/&gt;
 *             &lt;enumeration value="oval"/&gt;
 *             &lt;enumeration value="lobe"/&gt;
 *             &lt;enumeration value="hybridPlus"/&gt;
 *             &lt;enumeration value="hybridMinus"/&gt;
 *             &lt;enumeration value="dz2Plus"/&gt;
 *             &lt;enumeration value="dz2Minus"/&gt;
 *             &lt;enumeration value="dxy"/&gt;
 *             &lt;enumeration value="sShaded"/&gt;
 *             &lt;enumeration value="sFilled"/&gt;
 *             &lt;enumeration value="ovalShaded"/&gt;
 *             &lt;enumeration value="ovalFilled"/&gt;
 *             &lt;enumeration value="lobeShaded"/&gt;
 *             &lt;enumeration value="pShaded"/&gt;
 *             &lt;enumeration value="lobeFilled"/&gt;
 *             &lt;enumeration value="pFilled"/&gt;
 *             &lt;enumeration value="hybridPlusFilled"/&gt;
 *             &lt;enumeration value="hybridMinusFilled"/&gt;
 *             &lt;enumeration value="dz2PlusFilled"/&gt;
 *             &lt;enumeration value="dz2MinusFilled"/&gt;
 *             &lt;enumeration value="dxyFilled"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="SymbolType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="LonePair"/&gt;
 *             &lt;enumeration value="Electron"/&gt;
 *             &lt;enumeration value="RadicalCation"/&gt;
 *             &lt;enumeration value="RadicalAnion"/&gt;
 *             &lt;enumeration value="CirclePlus"/&gt;
 *             &lt;enumeration value="CircleMinus"/&gt;
 *             &lt;enumeration value="Dagger"/&gt;
 *             &lt;enumeration value="DoubleDagger"/&gt;
 *             &lt;enumeration value="Plus"/&gt;
 *             &lt;enumeration value="Minus"/&gt;
 *             &lt;enumeration value="Racemic"/&gt;
 *             &lt;enumeration value="Absolute"/&gt;
 *             &lt;enumeration value="Relative"/&gt;
 *             &lt;enumeration value="LonePairBar"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="FrameType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="HeadSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LipSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="AngularSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="IgnoreWarnings" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Warning" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Visible" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="BoldWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionFont" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CaptionFace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="BracketUsage"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Anypolymer"/&gt;
 *             &lt;enumeration value="Component"/&gt;
 *             &lt;enumeration value="Copolymer"/&gt;
 *             &lt;enumeration value="CopolymerAlternating"/&gt;
 *             &lt;enumeration value="CopolymerBlock"/&gt;
 *             &lt;enumeration value="CopolymerRandom"/&gt;
 *             &lt;enumeration value="Crosslink"/&gt;
 *             &lt;enumeration value="Generic"/&gt;
 *             &lt;enumeration value="Graft"/&gt;
 *             &lt;enumeration value="Mer"/&gt;
 *             &lt;enumeration value="MixtureOrdered"/&gt;
 *             &lt;enumeration value="MixtureUnordered"/&gt;
 *             &lt;enumeration value="Modification"/&gt;
 *             &lt;enumeration value="Monomer"/&gt;
 *             &lt;enumeration value="MultipleGroup"/&gt;
 *             &lt;enumeration value="SRU"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PolymerRepeatPattern"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="HeadToTail"/&gt;
 *             &lt;enumeration value="HeadToHead"/&gt;
 *             &lt;enumeration value="EitherUnknown"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="PolymerFlipType"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="NoFlip"/&gt;
 *             &lt;enumeration value="Flip"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Head3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Tail3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Center3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="MajorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="MinorAxisEnd3D" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ShadowSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="CornerRadius" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="FadePercent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrRepresentOrT"
})
@XmlRootElement(name = "graphic")
public class Graphic {

    @XmlElements({
        @XmlElement(name = "objecttag", type = Objecttag.class),
        @XmlElement(name = "represent", type = Represent.class),
        @XmlElement(name = "t", type = T.class)
    })
    protected List<Object> objecttagOrRepresentOrT;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "SupersededBy")
    @XmlSchemaType(name = "anySimpleType")
    protected String supersededBy;
    @XmlAttribute(name = "color")
    @XmlSchemaType(name = "anySimpleType")
    protected String color;
    @XmlAttribute(name = "bgcolor")
    @XmlSchemaType(name = "anySimpleType")
    protected String bgcolor;
    @XmlAttribute(name = "Z")
    @XmlSchemaType(name = "anySimpleType")
    protected String z;
    @XmlAttribute(name = "BoundingBox")
    @XmlSchemaType(name = "anySimpleType")
    protected String boundingBox;
    @XmlAttribute(name = "GraphicType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String graphicType;
    @XmlAttribute(name = "LineType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lineType;
    @XmlAttribute(name = "ArrowType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String arrowType;
    @XmlAttribute(name = "BracketType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bracketType;
    @XmlAttribute(name = "RectangleType")
    @XmlSchemaType(name = "anySimpleType")
    protected String rectangleType;
    @XmlAttribute(name = "OvalType")
    @XmlSchemaType(name = "anySimpleType")
    protected String ovalType;
    @XmlAttribute(name = "OrbitalType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orbitalType;
    @XmlAttribute(name = "SymbolType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String symbolType;
    @XmlAttribute(name = "FrameType")
    @XmlSchemaType(name = "anySimpleType")
    protected String frameType;
    @XmlAttribute(name = "HeadSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String headSize;
    @XmlAttribute(name = "LipSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String lipSize;
    @XmlAttribute(name = "AngularSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String angularSize;
    @XmlAttribute(name = "IgnoreWarnings")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignoreWarnings;
    @XmlAttribute(name = "Warning")
    @XmlSchemaType(name = "anySimpleType")
    protected String warning;
    @XmlAttribute(name = "Visible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visible;
    @XmlAttribute(name = "BoldWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String boldWidth;
    @XmlAttribute(name = "LineWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String lineWidth;
    @XmlAttribute(name = "CaptionFont")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionFont;
    @XmlAttribute(name = "CaptionSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionSize;
    @XmlAttribute(name = "CaptionFace")
    @XmlSchemaType(name = "anySimpleType")
    protected String captionFace;
    @XmlAttribute(name = "BracketUsage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bracketUsage;
    @XmlAttribute(name = "PolymerRepeatPattern")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String polymerRepeatPattern;
    @XmlAttribute(name = "PolymerFlipType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String polymerFlipType;
    @XmlAttribute(name = "Head3D")
    @XmlSchemaType(name = "anySimpleType")
    protected String head3D;
    @XmlAttribute(name = "Tail3D")
    @XmlSchemaType(name = "anySimpleType")
    protected String tail3D;
    @XmlAttribute(name = "Center3D")
    @XmlSchemaType(name = "anySimpleType")
    protected String center3D;
    @XmlAttribute(name = "MajorAxisEnd3D")
    @XmlSchemaType(name = "anySimpleType")
    protected String majorAxisEnd3D;
    @XmlAttribute(name = "MinorAxisEnd3D")
    @XmlSchemaType(name = "anySimpleType")
    protected String minorAxisEnd3D;
    @XmlAttribute(name = "ShadowSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String shadowSize;
    @XmlAttribute(name = "CornerRadius")
    @XmlSchemaType(name = "anySimpleType")
    protected String cornerRadius;
    @XmlAttribute(name = "FadePercent")
    @XmlSchemaType(name = "anySimpleType")
    protected String fadePercent;

    /**
     * Gets the value of the objecttagOrRepresentOrT property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrRepresentOrT property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrRepresentOrT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objecttag }
     * {@link Represent }
     * {@link T }
     * 
     * 
     */
    public List<Object> getObjecttagOrRepresentOrT() {
        if (objecttagOrRepresentOrT == null) {
            objecttagOrRepresentOrT = new ArrayList<Object>();
        }
        return this.objecttagOrRepresentOrT;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the supersededBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersededBy() {
        return supersededBy;
    }

    /**
     * Sets the value of the supersededBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersededBy(String value) {
        this.supersededBy = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the bgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * Sets the value of the bgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgcolor(String value) {
        this.bgcolor = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ(String value) {
        this.z = value;
    }

    /**
     * Gets the value of the boundingBox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundingBox() {
        return boundingBox;
    }

    /**
     * Sets the value of the boundingBox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundingBox(String value) {
        this.boundingBox = value;
    }

    /**
     * Gets the value of the graphicType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicType() {
        if (graphicType == null) {
            return "Undefined";
        } else {
            return graphicType;
        }
    }

    /**
     * Sets the value of the graphicType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicType(String value) {
        this.graphicType = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        return lineType;
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the arrowType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowType() {
        return arrowType;
    }

    /**
     * Sets the value of the arrowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowType(String value) {
        this.arrowType = value;
    }

    /**
     * Gets the value of the bracketType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBracketType() {
        return bracketType;
    }

    /**
     * Sets the value of the bracketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBracketType(String value) {
        this.bracketType = value;
    }

    /**
     * Gets the value of the rectangleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRectangleType() {
        return rectangleType;
    }

    /**
     * Sets the value of the rectangleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRectangleType(String value) {
        this.rectangleType = value;
    }

    /**
     * Gets the value of the ovalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOvalType() {
        return ovalType;
    }

    /**
     * Sets the value of the ovalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOvalType(String value) {
        this.ovalType = value;
    }

    /**
     * Gets the value of the orbitalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalType() {
        return orbitalType;
    }

    /**
     * Sets the value of the orbitalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalType(String value) {
        this.orbitalType = value;
    }

    /**
     * Gets the value of the symbolType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbolType() {
        return symbolType;
    }

    /**
     * Sets the value of the symbolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbolType(String value) {
        this.symbolType = value;
    }

    /**
     * Gets the value of the frameType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameType() {
        return frameType;
    }

    /**
     * Sets the value of the frameType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameType(String value) {
        this.frameType = value;
    }

    /**
     * Gets the value of the headSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadSize() {
        return headSize;
    }

    /**
     * Sets the value of the headSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadSize(String value) {
        this.headSize = value;
    }

    /**
     * Gets the value of the lipSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLipSize() {
        return lipSize;
    }

    /**
     * Sets the value of the lipSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLipSize(String value) {
        this.lipSize = value;
    }

    /**
     * Gets the value of the angularSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAngularSize() {
        return angularSize;
    }

    /**
     * Sets the value of the angularSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAngularSize(String value) {
        this.angularSize = value;
    }

    /**
     * Gets the value of the ignoreWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreWarnings() {
        if (ignoreWarnings == null) {
            return "no";
        } else {
            return ignoreWarnings;
        }
    }

    /**
     * Sets the value of the ignoreWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreWarnings(String value) {
        this.ignoreWarnings = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarning(String value) {
        this.warning = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "yes";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the boldWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoldWidth() {
        return boldWidth;
    }

    /**
     * Sets the value of the boldWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoldWidth(String value) {
        this.boldWidth = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineWidth(String value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the captionFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFont() {
        return captionFont;
    }

    /**
     * Sets the value of the captionFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFont(String value) {
        this.captionFont = value;
    }

    /**
     * Gets the value of the captionSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionSize() {
        return captionSize;
    }

    /**
     * Sets the value of the captionSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionSize(String value) {
        this.captionSize = value;
    }

    /**
     * Gets the value of the captionFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaptionFace() {
        return captionFace;
    }

    /**
     * Sets the value of the captionFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaptionFace(String value) {
        this.captionFace = value;
    }

    /**
     * Gets the value of the bracketUsage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBracketUsage() {
        return bracketUsage;
    }

    /**
     * Sets the value of the bracketUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBracketUsage(String value) {
        this.bracketUsage = value;
    }

    /**
     * Gets the value of the polymerRepeatPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolymerRepeatPattern() {
        return polymerRepeatPattern;
    }

    /**
     * Sets the value of the polymerRepeatPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolymerRepeatPattern(String value) {
        this.polymerRepeatPattern = value;
    }

    /**
     * Gets the value of the polymerFlipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolymerFlipType() {
        return polymerFlipType;
    }

    /**
     * Sets the value of the polymerFlipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolymerFlipType(String value) {
        this.polymerFlipType = value;
    }

    /**
     * Gets the value of the head3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHead3D() {
        return head3D;
    }

    /**
     * Sets the value of the head3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHead3D(String value) {
        this.head3D = value;
    }

    /**
     * Gets the value of the tail3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTail3D() {
        return tail3D;
    }

    /**
     * Sets the value of the tail3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTail3D(String value) {
        this.tail3D = value;
    }

    /**
     * Gets the value of the center3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenter3D() {
        return center3D;
    }

    /**
     * Sets the value of the center3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenter3D(String value) {
        this.center3D = value;
    }

    /**
     * Gets the value of the majorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorAxisEnd3D() {
        return majorAxisEnd3D;
    }

    /**
     * Sets the value of the majorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorAxisEnd3D(String value) {
        this.majorAxisEnd3D = value;
    }

    /**
     * Gets the value of the minorAxisEnd3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinorAxisEnd3D() {
        return minorAxisEnd3D;
    }

    /**
     * Sets the value of the minorAxisEnd3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinorAxisEnd3D(String value) {
        this.minorAxisEnd3D = value;
    }

    /**
     * Gets the value of the shadowSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowSize() {
        return shadowSize;
    }

    /**
     * Sets the value of the shadowSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowSize(String value) {
        this.shadowSize = value;
    }

    /**
     * Gets the value of the cornerRadius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCornerRadius() {
        return cornerRadius;
    }

    /**
     * Sets the value of the cornerRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCornerRadius(String value) {
        this.cornerRadius = value;
    }

    /**
     * Gets the value of the fadePercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFadePercent() {
        return fadePercent;
    }

    /**
     * Sets the value of the fadePercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFadePercent(String value) {
        this.fadePercent = value;
    }

}
