//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{}objecttag"/&gt;
 *         &lt;element ref="{}t"/&gt;
 *         &lt;element ref="{}fragment"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="p" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="xyz" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="SupersededBy" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="bgcolor" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Z" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Element" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" default="6" /&gt;
 *       &lt;attribute name="LabelDisplay" default="Auto"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Auto"/&gt;
 *             &lt;enumeration value="Left"/&gt;
 *             &lt;enumeration value="Center"/&gt;
 *             &lt;enumeration value="Right"/&gt;
 *             &lt;enumeration value="Above"/&gt;
 *             &lt;enumeration value="Below"/&gt;
 *             &lt;enumeration value="Best"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="NodeType" default="Element"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Element"/&gt;
 *             &lt;enumeration value="ElementList"/&gt;
 *             &lt;enumeration value="ElementListNickname"/&gt;
 *             &lt;enumeration value="Nickname"/&gt;
 *             &lt;enumeration value="Fragment"/&gt;
 *             &lt;enumeration value="Formula"/&gt;
 *             &lt;enumeration value="GenericNickname"/&gt;
 *             &lt;enumeration value="AnonymousAlternativeGroup"/&gt;
 *             &lt;enumeration value="NamedAlternativeGroup"/&gt;
 *             &lt;enumeration value="MultiAttachment"/&gt;
 *             &lt;enumeration value="VariableAttachment"/&gt;
 *             &lt;enumeration value="ExternalConnectionPoint"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ElementList" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="GenericList" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Formula" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Isotope" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Charge" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Radical" default="None"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="None"/&gt;
 *             &lt;enumeration value="Singlet"/&gt;
 *             &lt;enumeration value="Doublet"/&gt;
 *             &lt;enumeration value="Triplet"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="FreeSites" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ImplicitHydrogens" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RingBondCount" default="Unspecified"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="SpiroOrHigher"/&gt;
 *             &lt;enumeration value="Fusion"/&gt;
 *             &lt;enumeration value="SimpleRing"/&gt;
 *             &lt;enumeration value="AsDrawn"/&gt;
 *             &lt;enumeration value="NoRingBonds"/&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="UnsaturatedBonds" default="Unspecified"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="MustBeAbsent"/&gt;
 *             &lt;enumeration value="MustBePresent"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RxnChange" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="RxnStereo" default="Unspecified"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Inversion"/&gt;
 *             &lt;enumeration value="Retention"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Translation" default="Equal"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Equal"/&gt;
 *             &lt;enumeration value="Broad"/&gt;
 *             &lt;enumeration value="Narrow"/&gt;
 *             &lt;enumeration value="Any"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="IsotopicAbundance" default="Unspecified"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Any"/&gt;
 *             &lt;enumeration value="Natural"/&gt;
 *             &lt;enumeration value="Enriched"/&gt;
 *             &lt;enumeration value="Deficient"/&gt;
 *             &lt;enumeration value="Nonnatural"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ExternalConnectionType" default="Unspecified"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unspecified"/&gt;
 *             &lt;enumeration value="Diamond"/&gt;
 *             &lt;enumeration value="Star"/&gt;
 *             &lt;enumeration value="PolymerBead"/&gt;
 *             &lt;enumeration value="Wavy"/&gt;
 *             &lt;enumeration value="Residue"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="AbnormalValence" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="NumHydrogens" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="HDot" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HDash" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Geometry" default="Unknown"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="Unknown"/&gt;
 *             &lt;enumeration value="1"/&gt;
 *             &lt;enumeration value="Linear"/&gt;
 *             &lt;enumeration value="Bent"/&gt;
 *             &lt;enumeration value="TrigonalPlanar"/&gt;
 *             &lt;enumeration value="TrigonalPyramidal"/&gt;
 *             &lt;enumeration value="SquarePlanar"/&gt;
 *             &lt;enumeration value="Tetrahedral"/&gt;
 *             &lt;enumeration value="TrigonalBipyramidal"/&gt;
 *             &lt;enumeration value="SquarePyramidal"/&gt;
 *             &lt;enumeration value="5"/&gt;
 *             &lt;enumeration value="Octahedral"/&gt;
 *             &lt;enumeration value="6"/&gt;
 *             &lt;enumeration value="7"/&gt;
 *             &lt;enumeration value="8"/&gt;
 *             &lt;enumeration value="9"/&gt;
 *             &lt;enumeration value="10"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="BondOrdering" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Attachments" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="GenericNickname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="AltGroupID" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="SubstituentsUpTo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="SubstituentsExactly" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="AS" default="U"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="U"/&gt;
 *             &lt;enumeration value="N"/&gt;
 *             &lt;enumeration value="R"/&gt;
 *             &lt;enumeration value="S"/&gt;
 *             &lt;enumeration value="r"/&gt;
 *             &lt;enumeration value="s"/&gt;
 *             &lt;enumeration value="u"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="AtomNumber" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="IgnoreWarnings" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="Warning" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="Visible" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomQuery" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomStereo" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomEnhancedStereo" default="yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowAtomNumber" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowTerminalCarbonLabels" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="ShowNonTerminalCarbonLabels" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="HideImplicitHydrogens" default="no"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *             &lt;enumeration value="yes"/&gt;
 *             &lt;enumeration value="no"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="LineWidth" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelFont" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelSize" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LabelFace" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LinkCountLow" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="LinkCountHigh" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="EnhancedStereoType" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="EnhancedStereoGroupNum" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttagOrTOrFragment"
})
@XmlRootElement(name = "n")
public class N {

    @XmlElements({
        @XmlElement(name = "objecttag", type = Objecttag.class),
        @XmlElement(name = "t", type = T.class),
        @XmlElement(name = "fragment", type = Fragment.class)
    })
    protected List<Object> objecttagOrTOrFragment;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "p")
    @XmlSchemaType(name = "anySimpleType")
    protected String p;
    @XmlAttribute(name = "xyz")
    @XmlSchemaType(name = "anySimpleType")
    protected String xyz;
    @XmlAttribute(name = "SupersededBy")
    @XmlSchemaType(name = "anySimpleType")
    protected String supersededBy;
    @XmlAttribute(name = "color")
    @XmlSchemaType(name = "anySimpleType")
    protected String color;
    @XmlAttribute(name = "bgcolor")
    @XmlSchemaType(name = "anySimpleType")
    protected String bgcolor;
    @XmlAttribute(name = "Z")
    @XmlSchemaType(name = "anySimpleType")
    protected String z;
    @XmlAttribute(name = "Element")
    @XmlSchemaType(name = "anySimpleType")
    protected String element;
    @XmlAttribute(name = "LabelDisplay")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String labelDisplay;
    @XmlAttribute(name = "NodeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nodeType;
    @XmlAttribute(name = "ElementList")
    @XmlSchemaType(name = "anySimpleType")
    protected String elementList;
    @XmlAttribute(name = "GenericList")
    @XmlSchemaType(name = "anySimpleType")
    protected String genericList;
    @XmlAttribute(name = "Formula")
    @XmlSchemaType(name = "anySimpleType")
    protected String formula;
    @XmlAttribute(name = "Isotope")
    @XmlSchemaType(name = "anySimpleType")
    protected String isotope;
    @XmlAttribute(name = "Charge")
    @XmlSchemaType(name = "anySimpleType")
    protected String charge;
    @XmlAttribute(name = "Radical")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String radical;
    @XmlAttribute(name = "FreeSites")
    @XmlSchemaType(name = "anySimpleType")
    protected String freeSites;
    @XmlAttribute(name = "ImplicitHydrogens")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String implicitHydrogens;
    @XmlAttribute(name = "RingBondCount")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ringBondCount;
    @XmlAttribute(name = "UnsaturatedBonds")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String unsaturatedBonds;
    @XmlAttribute(name = "RxnChange")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rxnChange;
    @XmlAttribute(name = "RxnStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rxnStereo;
    @XmlAttribute(name = "Translation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String translation;
    @XmlAttribute(name = "IsotopicAbundance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String isotopicAbundance;
    @XmlAttribute(name = "ExternalConnectionType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String externalConnectionType;
    @XmlAttribute(name = "AbnormalValence")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String abnormalValence;
    @XmlAttribute(name = "NumHydrogens")
    @XmlSchemaType(name = "anySimpleType")
    protected String numHydrogens;
    @XmlAttribute(name = "HDot")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hDot;
    @XmlAttribute(name = "HDash")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hDash;
    @XmlAttribute(name = "Geometry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String geometry;
    @XmlAttribute(name = "BondOrdering")
    @XmlSchemaType(name = "anySimpleType")
    protected String bondOrdering;
    @XmlAttribute(name = "Attachments")
    @XmlSchemaType(name = "anySimpleType")
    protected String attachments;
    @XmlAttribute(name = "GenericNickname")
    @XmlSchemaType(name = "anySimpleType")
    protected String genericNickname;
    @XmlAttribute(name = "AltGroupID")
    @XmlSchemaType(name = "anySimpleType")
    protected String altGroupID;
    @XmlAttribute(name = "SubstituentsUpTo")
    @XmlSchemaType(name = "anySimpleType")
    protected String substituentsUpTo;
    @XmlAttribute(name = "SubstituentsExactly")
    @XmlSchemaType(name = "anySimpleType")
    protected String substituentsExactly;
    @XmlAttribute(name = "AS")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String as;
    @XmlAttribute(name = "AtomNumber")
    @XmlSchemaType(name = "anySimpleType")
    protected String atomNumber;
    @XmlAttribute(name = "IgnoreWarnings")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ignoreWarnings;
    @XmlAttribute(name = "Warning")
    @XmlSchemaType(name = "anySimpleType")
    protected String warning;
    @XmlAttribute(name = "Visible")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String visible;
    @XmlAttribute(name = "ShowAtomQuery")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomQuery;
    @XmlAttribute(name = "ShowAtomStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomStereo;
    @XmlAttribute(name = "ShowAtomEnhancedStereo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomEnhancedStereo;
    @XmlAttribute(name = "ShowAtomNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showAtomNumber;
    @XmlAttribute(name = "ShowTerminalCarbonLabels")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showTerminalCarbonLabels;
    @XmlAttribute(name = "ShowNonTerminalCarbonLabels")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String showNonTerminalCarbonLabels;
    @XmlAttribute(name = "HideImplicitHydrogens")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hideImplicitHydrogens;
    @XmlAttribute(name = "LineWidth")
    @XmlSchemaType(name = "anySimpleType")
    protected String lineWidth;
    @XmlAttribute(name = "LabelFont")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelFont;
    @XmlAttribute(name = "LabelSize")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelSize;
    @XmlAttribute(name = "LabelFace")
    @XmlSchemaType(name = "anySimpleType")
    protected String labelFace;
    @XmlAttribute(name = "LinkCountLow")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkCountLow;
    @XmlAttribute(name = "LinkCountHigh")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkCountHigh;
    @XmlAttribute(name = "EnhancedStereoType")
    @XmlSchemaType(name = "anySimpleType")
    protected String enhancedStereoType;
    @XmlAttribute(name = "EnhancedStereoGroupNum")
    @XmlSchemaType(name = "anySimpleType")
    protected String enhancedStereoGroupNum;

    /**
     * Gets the value of the objecttagOrTOrFragment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttagOrTOrFragment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttagOrTOrFragment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objecttag }
     * {@link T }
     * {@link Fragment }
     * 
     * 
     */
    public List<Object> getObjecttagOrTOrFragment() {
        if (objecttagOrTOrFragment == null) {
            objecttagOrTOrFragment = new ArrayList<Object>();
        }
        return this.objecttagOrTOrFragment;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the p property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP(String value) {
        this.p = value;
    }

    /**
     * Gets the value of the xyz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXyz() {
        return xyz;
    }

    /**
     * Sets the value of the xyz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXyz(String value) {
        this.xyz = value;
    }

    /**
     * Gets the value of the supersededBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupersededBy() {
        return supersededBy;
    }

    /**
     * Sets the value of the supersededBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupersededBy(String value) {
        this.supersededBy = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the bgcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgcolor() {
        return bgcolor;
    }

    /**
     * Sets the value of the bgcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgcolor(String value) {
        this.bgcolor = value;
    }

    /**
     * Gets the value of the z property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ() {
        return z;
    }

    /**
     * Sets the value of the z property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ(String value) {
        this.z = value;
    }

    /**
     * Gets the value of the element property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElement() {
        if (element == null) {
            return "6";
        } else {
            return element;
        }
    }

    /**
     * Sets the value of the element property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElement(String value) {
        this.element = value;
    }

    /**
     * Gets the value of the labelDisplay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelDisplay() {
        if (labelDisplay == null) {
            return "Auto";
        } else {
            return labelDisplay;
        }
    }

    /**
     * Sets the value of the labelDisplay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelDisplay(String value) {
        this.labelDisplay = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeType() {
        if (nodeType == null) {
            return "Element";
        } else {
            return nodeType;
        }
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeType(String value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the elementList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementList() {
        return elementList;
    }

    /**
     * Sets the value of the elementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementList(String value) {
        this.elementList = value;
    }

    /**
     * Gets the value of the genericList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericList() {
        return genericList;
    }

    /**
     * Sets the value of the genericList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericList(String value) {
        this.genericList = value;
    }

    /**
     * Gets the value of the formula property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormula() {
        return formula;
    }

    /**
     * Sets the value of the formula property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormula(String value) {
        this.formula = value;
    }

    /**
     * Gets the value of the isotope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsotope() {
        return isotope;
    }

    /**
     * Sets the value of the isotope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsotope(String value) {
        this.isotope = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharge(String value) {
        this.charge = value;
    }

    /**
     * Gets the value of the radical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadical() {
        if (radical == null) {
            return "None";
        } else {
            return radical;
        }
    }

    /**
     * Sets the value of the radical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadical(String value) {
        this.radical = value;
    }

    /**
     * Gets the value of the freeSites property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeSites() {
        return freeSites;
    }

    /**
     * Sets the value of the freeSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeSites(String value) {
        this.freeSites = value;
    }

    /**
     * Gets the value of the implicitHydrogens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplicitHydrogens() {
        if (implicitHydrogens == null) {
            return "no";
        } else {
            return implicitHydrogens;
        }
    }

    /**
     * Sets the value of the implicitHydrogens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplicitHydrogens(String value) {
        this.implicitHydrogens = value;
    }

    /**
     * Gets the value of the ringBondCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRingBondCount() {
        if (ringBondCount == null) {
            return "Unspecified";
        } else {
            return ringBondCount;
        }
    }

    /**
     * Sets the value of the ringBondCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRingBondCount(String value) {
        this.ringBondCount = value;
    }

    /**
     * Gets the value of the unsaturatedBonds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnsaturatedBonds() {
        if (unsaturatedBonds == null) {
            return "Unspecified";
        } else {
            return unsaturatedBonds;
        }
    }

    /**
     * Sets the value of the unsaturatedBonds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnsaturatedBonds(String value) {
        this.unsaturatedBonds = value;
    }

    /**
     * Gets the value of the rxnChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRxnChange() {
        if (rxnChange == null) {
            return "no";
        } else {
            return rxnChange;
        }
    }

    /**
     * Sets the value of the rxnChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRxnChange(String value) {
        this.rxnChange = value;
    }

    /**
     * Gets the value of the rxnStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRxnStereo() {
        if (rxnStereo == null) {
            return "Unspecified";
        } else {
            return rxnStereo;
        }
    }

    /**
     * Sets the value of the rxnStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRxnStereo(String value) {
        this.rxnStereo = value;
    }

    /**
     * Gets the value of the translation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranslation() {
        if (translation == null) {
            return "Equal";
        } else {
            return translation;
        }
    }

    /**
     * Sets the value of the translation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranslation(String value) {
        this.translation = value;
    }

    /**
     * Gets the value of the isotopicAbundance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsotopicAbundance() {
        if (isotopicAbundance == null) {
            return "Unspecified";
        } else {
            return isotopicAbundance;
        }
    }

    /**
     * Sets the value of the isotopicAbundance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsotopicAbundance(String value) {
        this.isotopicAbundance = value;
    }

    /**
     * Gets the value of the externalConnectionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalConnectionType() {
        if (externalConnectionType == null) {
            return "Unspecified";
        } else {
            return externalConnectionType;
        }
    }

    /**
     * Sets the value of the externalConnectionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalConnectionType(String value) {
        this.externalConnectionType = value;
    }

    /**
     * Gets the value of the abnormalValence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbnormalValence() {
        if (abnormalValence == null) {
            return "no";
        } else {
            return abnormalValence;
        }
    }

    /**
     * Sets the value of the abnormalValence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbnormalValence(String value) {
        this.abnormalValence = value;
    }

    /**
     * Gets the value of the numHydrogens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumHydrogens() {
        return numHydrogens;
    }

    /**
     * Sets the value of the numHydrogens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumHydrogens(String value) {
        this.numHydrogens = value;
    }

    /**
     * Gets the value of the hDot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDot() {
        if (hDot == null) {
            return "no";
        } else {
            return hDot;
        }
    }

    /**
     * Sets the value of the hDot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDot(String value) {
        this.hDot = value;
    }

    /**
     * Gets the value of the hDash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHDash() {
        if (hDash == null) {
            return "no";
        } else {
            return hDash;
        }
    }

    /**
     * Sets the value of the hDash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHDash(String value) {
        this.hDash = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeometry() {
        if (geometry == null) {
            return "Unknown";
        } else {
            return geometry;
        }
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeometry(String value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the bondOrdering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBondOrdering() {
        return bondOrdering;
    }

    /**
     * Sets the value of the bondOrdering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBondOrdering(String value) {
        this.bondOrdering = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachments(String value) {
        this.attachments = value;
    }

    /**
     * Gets the value of the genericNickname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericNickname() {
        return genericNickname;
    }

    /**
     * Sets the value of the genericNickname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericNickname(String value) {
        this.genericNickname = value;
    }

    /**
     * Gets the value of the altGroupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltGroupID() {
        return altGroupID;
    }

    /**
     * Sets the value of the altGroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltGroupID(String value) {
        this.altGroupID = value;
    }

    /**
     * Gets the value of the substituentsUpTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstituentsUpTo() {
        return substituentsUpTo;
    }

    /**
     * Sets the value of the substituentsUpTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstituentsUpTo(String value) {
        this.substituentsUpTo = value;
    }

    /**
     * Gets the value of the substituentsExactly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstituentsExactly() {
        return substituentsExactly;
    }

    /**
     * Sets the value of the substituentsExactly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstituentsExactly(String value) {
        this.substituentsExactly = value;
    }

    /**
     * Gets the value of the as property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAS() {
        if (as == null) {
            return "U";
        } else {
            return as;
        }
    }

    /**
     * Sets the value of the as property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAS(String value) {
        this.as = value;
    }

    /**
     * Gets the value of the atomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtomNumber() {
        return atomNumber;
    }

    /**
     * Sets the value of the atomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtomNumber(String value) {
        this.atomNumber = value;
    }

    /**
     * Gets the value of the ignoreWarnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreWarnings() {
        if (ignoreWarnings == null) {
            return "no";
        } else {
            return ignoreWarnings;
        }
    }

    /**
     * Sets the value of the ignoreWarnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreWarnings(String value) {
        this.ignoreWarnings = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarning(String value) {
        this.warning = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisible() {
        if (visible == null) {
            return "yes";
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisible(String value) {
        this.visible = value;
    }

    /**
     * Gets the value of the showAtomQuery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomQuery() {
        if (showAtomQuery == null) {
            return "yes";
        } else {
            return showAtomQuery;
        }
    }

    /**
     * Sets the value of the showAtomQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomQuery(String value) {
        this.showAtomQuery = value;
    }

    /**
     * Gets the value of the showAtomStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomStereo() {
        if (showAtomStereo == null) {
            return "no";
        } else {
            return showAtomStereo;
        }
    }

    /**
     * Sets the value of the showAtomStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomStereo(String value) {
        this.showAtomStereo = value;
    }

    /**
     * Gets the value of the showAtomEnhancedStereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomEnhancedStereo() {
        if (showAtomEnhancedStereo == null) {
            return "yes";
        } else {
            return showAtomEnhancedStereo;
        }
    }

    /**
     * Sets the value of the showAtomEnhancedStereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomEnhancedStereo(String value) {
        this.showAtomEnhancedStereo = value;
    }

    /**
     * Gets the value of the showAtomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAtomNumber() {
        if (showAtomNumber == null) {
            return "no";
        } else {
            return showAtomNumber;
        }
    }

    /**
     * Sets the value of the showAtomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAtomNumber(String value) {
        this.showAtomNumber = value;
    }

    /**
     * Gets the value of the showTerminalCarbonLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowTerminalCarbonLabels() {
        if (showTerminalCarbonLabels == null) {
            return "no";
        } else {
            return showTerminalCarbonLabels;
        }
    }

    /**
     * Sets the value of the showTerminalCarbonLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowTerminalCarbonLabels(String value) {
        this.showTerminalCarbonLabels = value;
    }

    /**
     * Gets the value of the showNonTerminalCarbonLabels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowNonTerminalCarbonLabels() {
        if (showNonTerminalCarbonLabels == null) {
            return "no";
        } else {
            return showNonTerminalCarbonLabels;
        }
    }

    /**
     * Sets the value of the showNonTerminalCarbonLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowNonTerminalCarbonLabels(String value) {
        this.showNonTerminalCarbonLabels = value;
    }

    /**
     * Gets the value of the hideImplicitHydrogens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideImplicitHydrogens() {
        if (hideImplicitHydrogens == null) {
            return "no";
        } else {
            return hideImplicitHydrogens;
        }
    }

    /**
     * Sets the value of the hideImplicitHydrogens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideImplicitHydrogens(String value) {
        this.hideImplicitHydrogens = value;
    }

    /**
     * Gets the value of the lineWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineWidth() {
        return lineWidth;
    }

    /**
     * Sets the value of the lineWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineWidth(String value) {
        this.lineWidth = value;
    }

    /**
     * Gets the value of the labelFont property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelFont() {
        return labelFont;
    }

    /**
     * Sets the value of the labelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelFont(String value) {
        this.labelFont = value;
    }

    /**
     * Gets the value of the labelSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelSize() {
        return labelSize;
    }

    /**
     * Sets the value of the labelSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelSize(String value) {
        this.labelSize = value;
    }

    /**
     * Gets the value of the labelFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelFace() {
        return labelFace;
    }

    /**
     * Sets the value of the labelFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelFace(String value) {
        this.labelFace = value;
    }

    /**
     * Gets the value of the linkCountLow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkCountLow() {
        return linkCountLow;
    }

    /**
     * Sets the value of the linkCountLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkCountLow(String value) {
        this.linkCountLow = value;
    }

    /**
     * Gets the value of the linkCountHigh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkCountHigh() {
        return linkCountHigh;
    }

    /**
     * Sets the value of the linkCountHigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkCountHigh(String value) {
        this.linkCountHigh = value;
    }

    /**
     * Gets the value of the enhancedStereoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedStereoType() {
        return enhancedStereoType;
    }

    /**
     * Sets the value of the enhancedStereoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedStereoType(String value) {
        this.enhancedStereoType = value;
    }

    /**
     * Gets the value of the enhancedStereoGroupNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedStereoGroupNum() {
        return enhancedStereoGroupNum;
    }

    /**
     * Sets the value of the enhancedStereoGroupNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedStereoGroupNum(String value) {
        this.enhancedStereoGroupNum = value;
    }

}
