//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}objecttag" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="RegionStart" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="RegionEnd" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="RegionOffset" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "objecttag"
})
@XmlRootElement(name = "plasmidregion")
public class Plasmidregion {

    protected List<Objecttag> objecttag;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "RegionStart")
    @XmlSchemaType(name = "anySimpleType")
    protected String regionStart;
    @XmlAttribute(name = "RegionEnd")
    @XmlSchemaType(name = "anySimpleType")
    protected String regionEnd;
    @XmlAttribute(name = "RegionOffset")
    @XmlSchemaType(name = "anySimpleType")
    protected String regionOffset;

    /**
     * Gets the value of the objecttag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objecttag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjecttag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Objecttag }
     * 
     * 
     */
    public List<Objecttag> getObjecttag() {
        if (objecttag == null) {
            objecttag = new ArrayList<Objecttag>();
        }
        return this.objecttag;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the regionStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionStart() {
        return regionStart;
    }

    /**
     * Sets the value of the regionStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionStart(String value) {
        this.regionStart = value;
    }

    /**
     * Gets the value of the regionEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionEnd() {
        return regionEnd;
    }

    /**
     * Sets the value of the regionEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionEnd(String value) {
        this.regionEnd = value;
    }

    /**
     * Gets the value of the regionOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionOffset() {
        return regionOffset;
    }

    /**
     * Sets the value of the regionOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionOffset(String value) {
        this.regionOffset = value;
    }

}
