//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 04:25:40 PM CST 
//


package cdxml.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepReactants" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepProducts" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepPlusses" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepArrows" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepObjectsAboveArrow" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepObjectsBelowArrow" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepAtomMap" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepAtomMapManual" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="ReactionStepAtomMapAuto" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "step")
public class Step {

    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "ReactionStepReactants")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepReactants;
    @XmlAttribute(name = "ReactionStepProducts")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepProducts;
    @XmlAttribute(name = "ReactionStepPlusses")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepPlusses;
    @XmlAttribute(name = "ReactionStepArrows")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepArrows;
    @XmlAttribute(name = "ReactionStepObjectsAboveArrow")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepObjectsAboveArrow;
    @XmlAttribute(name = "ReactionStepObjectsBelowArrow")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepObjectsBelowArrow;
    @XmlAttribute(name = "ReactionStepAtomMap")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepAtomMap;
    @XmlAttribute(name = "ReactionStepAtomMapManual")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepAtomMapManual;
    @XmlAttribute(name = "ReactionStepAtomMapAuto")
    @XmlSchemaType(name = "anySimpleType")
    protected String reactionStepAtomMapAuto;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the reactionStepReactants property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepReactants() {
        return reactionStepReactants;
    }

    /**
     * Sets the value of the reactionStepReactants property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepReactants(String value) {
        this.reactionStepReactants = value;
    }

    /**
     * Gets the value of the reactionStepProducts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepProducts() {
        return reactionStepProducts;
    }

    /**
     * Sets the value of the reactionStepProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepProducts(String value) {
        this.reactionStepProducts = value;
    }

    /**
     * Gets the value of the reactionStepPlusses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepPlusses() {
        return reactionStepPlusses;
    }

    /**
     * Sets the value of the reactionStepPlusses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepPlusses(String value) {
        this.reactionStepPlusses = value;
    }

    /**
     * Gets the value of the reactionStepArrows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepArrows() {
        return reactionStepArrows;
    }

    /**
     * Sets the value of the reactionStepArrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepArrows(String value) {
        this.reactionStepArrows = value;
    }

    /**
     * Gets the value of the reactionStepObjectsAboveArrow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepObjectsAboveArrow() {
        return reactionStepObjectsAboveArrow;
    }

    /**
     * Sets the value of the reactionStepObjectsAboveArrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepObjectsAboveArrow(String value) {
        this.reactionStepObjectsAboveArrow = value;
    }

    /**
     * Gets the value of the reactionStepObjectsBelowArrow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepObjectsBelowArrow() {
        return reactionStepObjectsBelowArrow;
    }

    /**
     * Sets the value of the reactionStepObjectsBelowArrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepObjectsBelowArrow(String value) {
        this.reactionStepObjectsBelowArrow = value;
    }

    /**
     * Gets the value of the reactionStepAtomMap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepAtomMap() {
        return reactionStepAtomMap;
    }

    /**
     * Sets the value of the reactionStepAtomMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepAtomMap(String value) {
        this.reactionStepAtomMap = value;
    }

    /**
     * Gets the value of the reactionStepAtomMapManual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepAtomMapManual() {
        return reactionStepAtomMapManual;
    }

    /**
     * Sets the value of the reactionStepAtomMapManual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepAtomMapManual(String value) {
        this.reactionStepAtomMapManual = value;
    }

    /**
     * Gets the value of the reactionStepAtomMapAuto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReactionStepAtomMapAuto() {
        return reactionStepAtomMapAuto;
    }

    /**
     * Sets the value of the reactionStepAtomMapAuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReactionStepAtomMapAuto(String value) {
        this.reactionStepAtomMapAuto = value;
    }

}
